baseURL: "http://anbox.io/"
absURL: "http://anbox.io/"
languageCode: "en-us"
title: "Anbox - Android in a Box"
theme: "hugo-creative-theme"

params:
    name: Anbox
    description: Android in a Box
    favicon: favicon.ico

    hero:
        slogan: "Android in a Box"
        subtitle: "Run Android applications on any GNU Linux operating system."
        buttonText: "Find out more"

    services:
        headline: "Features"
        list:
            - icon: fa-github
              title: Open Source
              description: |
                The whole source is available as Open Source. No binary blobs!
            - icon: fa-laptop
              title: No limits
              description: |
                As Anbox is running an entire Android system there are no limits which applications you can run.
            - icon: fa-lock
              title: Secure
              description: |
                Anbox puts Android apps into a tightly sealed box without direct access to hardware or your data.
            - icon: fa-clock-o
              title: Performant
              description: |
                Runs Android without hardware virtualization and seamlessly bridges over hardware acceleration features.
            - icon: fa-microchip
              title: Integrated
              description: |
                Tightly integrated with the host operating system to offer a reach feature set.
